export type ProblemListItem = {
	id: string;
	title: string;
	difficulty: "Easy" | "Medium" | "Hard";
	topics: string[];
	companies: string[];
	order: number;
	videoId?: string;
	link?: string;
};

export const problemsMeta: ProblemListItem[] = [
	{
		id: "two-sum",
		title: "Two Sum",
		difficulty: "Easy",
		topics: ["Array & Hashing"],
		companies: ["Google", "Amazon", "Adobe", "Salesforce"],
		order: 1,
		videoId: "8-k1C6ehKuw",
	},
	{
		id: "contains-duplicate",
		title: "Contains Duplicate",
		difficulty: "Easy",
		topics: ["Array & Hashing"],
		companies: ["Netflix", "Atlassian", "Microsoft"],
		order: 2,
	},
	{
		id: "valid-anagram",
		title: "Valid Anagram",
		difficulty: "Easy",
		topics: ["Array & Hashing"],
		companies: ["Microsoft", "Walmart Labs", "Two Sigma", "eBay"],
		order: 3,
	},
	{
		id: "group-anagrams",
		title: "Group Anagrams",
		difficulty: "Medium",
		topics: ["Array & Hashing"],
		companies: ["Meta", "Bloomberg", "Cisco", "Atlassian"],
		order: 4,
	},
	{
		id: "top-k-frequent-elements",
		title: "Top K Frequent Elements",
		difficulty: "Medium",
		topics: ["Array & Hashing"],
		companies: ["Amazon", "Microsoft"],
		order: 5,
	},
	{
		id: "product-of-array-except-self",
		title: "Product of Array Except Self",
		difficulty: "Medium",
		topics: ["Array & Hashing"],
		companies: ["eBay", "Apple"],
		order: 6,
	},
	{
		id: "longest-consecutive-sequence",
		title: "Longest Consecutive Sequence",
		difficulty: "Medium",
		topics: ["Array & Hashing"],
		companies: ["Google", "Oracle", "Uber"],
		order: 7,
	},
	{
		id: "encode-and-decode-strings",
		title: "Encode and Decode Strings",
		difficulty: "Medium",
		topics: ["Array & Hashing"],
		companies: ["Amazon", "Apple"],
		order: 8,
	},
	{
		id: "valid-sudoku",
		title: "Valid Sudoku",
		difficulty: "Medium",
		topics: ["Array & Hashing"],
		companies: ["Cisco", "DoorDash", "ByteDance"],
		order: 9,
	},
	{
		id: "majority-element",
		title: "Majority Element",
		difficulty: "Easy",
		topics: ["Array & Hashing"],
		companies: ["DoorDash", "Uber", "eBay"],
		order: 10,
	},
	{
		id: "missing-number",
		title: "Missing Number",
		difficulty: "Easy",
		topics: ["Array & Hashing"],
		companies: ["Netflix", "Walmart Labs", "Cisco", "Snap"],
		order: 11,
	},
	{
		id: "find-all-numbers-disappeared-in-an-array",
		title: "Find All Numbers Disappeared in an Array",
		difficulty: "Easy",
		topics: ["Array & Hashing"],
		companies: ["Airbnb", "Snap"],
		order: 12,
	},
	{
		id: "single-number",
		title: "Single Number",
		difficulty: "Easy",
		topics: ["Array & Hashing"],
		companies: ["Bloomberg", "PayPal", "LinkedIn", "Oracle"],
		order: 13,
	},
	{
		id: "single-number-ii",
		title: "Single Number II",
		difficulty: "Medium",
		topics: ["Array & Hashing"],
		companies: ["Microsoft", "Uber", "Salesforce"],
		order: 14,
	},
	{
		id: "single-number-iii",
		title: "Single Number III",
		difficulty: "Medium",
		topics: ["Array & Hashing"],
		companies: ["Amazon", "Meta"],
		order: 15,
	},
	{
		id: "intersection-of-two-arrays",
		title: "Intersection of Two Arrays",
		difficulty: "Easy",
		topics: ["Array & Hashing"],
		companies: ["DoorDash", "Uber", "LinkedIn", "Meta"],
		order: 16,
	},
	{
		id: "intersection-of-two-arrays-ii",
		title: "Intersection of Two Arrays II",
		difficulty: "Easy",
		topics: ["Array & Hashing"],
		companies: ["Amazon", "Uber"],
		order: 17,
	},
	{
		id: "sort-colors",
		title: "Sort Colors",
		difficulty: "Medium",
		topics: ["Array & Hashing"],
		companies: ["Spotify", "Yahoo", "Bloomberg", "Meta"],
		order: 18,
	},
	{
		id: "move-zeroes",
		title: "Move Zeroes",
		difficulty: "Easy",
		topics: ["Array & Hashing"],
		companies: ["Pinterest", "Airbnb", "Google", "Spotify"],
		order: 19,
	},
	{
		id: "rotate-array",
		title: "Rotate Array",
		difficulty: "Medium",
		topics: ["Array & Hashing"],
		companies: ["Amazon", "LinkedIn", "Meta", "Bloomberg"],
		order: 20,
	},
	{
		id: "best-time-to-buy-and-sell-stock",
		title: "Best Time to Buy and Sell Stock",
		difficulty: "Easy",
		topics: ["Array & Hashing"],
		companies: ["PayPal", "Apple"],
		order: 21,
	},
	{
		id: "best-time-to-buy-and-sell-stock-ii",
		title: "Best Time to Buy and Sell Stock II",
		difficulty: "Medium",
		topics: ["Array & Hashing"],
		companies: ["Apple", "Snap"],
		order: 22,
	},
	{
		id: "subarray-sum-equals-k",
		title: "Subarray Sum Equals K",
		difficulty: "Medium",
		topics: ["Array & Hashing"],
		companies: ["Uber", "Netflix", "LinkedIn"],
		order: 23,
	},
	{
		id: "continuous-subarray-sum",
		title: "Continuous Subarray Sum",
		difficulty: "Medium",
		topics: ["Array & Hashing"],
		companies: ["Atlassian", "Microsoft"],
		order: 24,
	},
	{
		id: "merge-sorted-array",
		title: "Merge Sorted Array",
		difficulty: "Easy",
		topics: ["Array & Hashing"],
		companies: ["Airbnb", "Apple", "Microsoft", "Goldman Sachs"],
		order: 25,
	},
	{
		id: "remove-duplicates-from-sorted-array",
		title: "Remove Duplicates from Sorted Array",
		difficulty: "Easy",
		topics: ["Array & Hashing"],
		companies: ["Uber", "DoorDash", "Google", "Netflix"],
		order: 26,
	},
	{
		id: "remove-element",
		title: "Remove Element",
		difficulty: "Easy",
		topics: ["Array & Hashing"],
		companies: ["Microsoft", "eBay", "Uber"],
		order: 27,
	},
	{
		id: "plus-one",
		title: "Plus One",
		difficulty: "Easy",
		topics: ["Array & Hashing"],
		companies: ["Uber", "Snap", "PayPal"],
		order: 28,
	},
	{
		id: "pascal-s-triangle",
		title: "Pascal's Triangle",
		difficulty: "Easy",
		topics: ["Array & Hashing"],
		companies: ["Microsoft", "Salesforce", "LinkedIn", "Pinterest"],
		order: 29,
	},
	{
		id: "first-missing-positive",
		title: "First Missing Positive",
		difficulty: "Hard",
		topics: ["Array & Hashing"],
		companies: ["LinkedIn", "Apple", "Pinterest", "Uber"],
		order: 30,
	},
	{
		id: "set-matrix-zeroes",
		title: "Set Matrix Zeroes",
		difficulty: "Medium",
		topics: ["Array & Hashing"],
		companies: ["Apple", "Google", "Salesforce"],
		order: 31,
	},
	{
		id: "valid-palindrome",
		title: "Valid Palindrome",
		difficulty: "Easy",
		topics: ["Two Pointers"],
		companies: ["Two Sigma", "PayPal", "Meta", "Atlassian"],
		order: 32,
	},
	{
		id: "3sum",
		title: "3Sum",
		difficulty: "Medium",
		topics: ["Two Pointers"],
		companies: ["Atlassian", "Microsoft"],
		order: 33,
	},
	{
		id: "3sum-closest",
		title: "3Sum Closest",
		difficulty: "Medium",
		topics: ["Two Pointers"],
		companies: ["Snap", "Airbnb"],
		order: 34,
	},
	{
		id: "4sum",
		title: "4Sum",
		difficulty: "Medium",
		topics: ["Two Pointers"],
		companies: ["Microsoft", "Apple", "Yahoo", "Cisco"],
		order: 35,
	},
	{
		id: "container-with-most-water",
		title: "Container With Most Water",
		difficulty: "Medium",
		topics: ["Two Pointers"],
		companies: ["Amazon", "Google"],
		order: 36,
	},
	{
		id: "trapping-rain-water",
		title: "Trapping Rain Water",
		difficulty: "Hard",
		topics: ["Two Pointers"],
		companies: ["Airbnb", "Uber"],
		order: 37,
	},
	{
		id: "sort-array-by-parity",
		title: "Sort Array By Parity",
		difficulty: "Easy",
		topics: ["Two Pointers"],
		companies: ["Apple", "PayPal"],
		order: 38,
	},
	{
		id: "remove-duplicates-from-sorted-array-ii",
		title: "Remove Duplicates from Sorted Array II",
		difficulty: "Medium",
		topics: ["Two Pointers"],
		companies: ["Meta", "Netflix", "Amazon"],
		order: 39,
	},
	{
		id: "backspace-string-compare",
		title: "Backspace String Compare",
		difficulty: "Easy",
		topics: ["Two Pointers"],
		companies: ["Microsoft", "Amazon"],
		order: 40,
	},
	{
		id: "squares-of-a-sorted-array",
		title: "Squares of a Sorted Array",
		difficulty: "Easy",
		topics: ["Two Pointers"],
		companies: ["Visa", "Bloomberg"],
		order: 41,
	},
	{
		id: "reverse-string",
		title: "Reverse String",
		difficulty: "Easy",
		topics: ["Two Pointers"],
		companies: ["Microsoft", "eBay", "Walmart Labs"],
		order: 42,
	},
	{
		id: "boats-to-save-people",
		title: "Boats to Save People",
		difficulty: "Medium",
		topics: ["Two Pointers"],
		companies: ["Cisco", "Oracle", "ByteDance"],
		order: 43,
	},
	{
		id: "two-sum-ii-input-array-is-sorted",
		title: "Two Sum II - Input Array Is Sorted",
		difficulty: "Medium",
		topics: ["Two Pointers"],
		companies: ["DoorDash", "Meta"],
		order: 44,
	},
	{
		id: "is-subsequence",
		title: "Is Subsequence",
		difficulty: "Easy",
		topics: ["Two Pointers"],
		companies: ["Google", "Spotify", "eBay"],
		order: 45,
	},
	{
		id: "reverse-vowels-of-a-string",
		title: "Reverse Vowels of a String",
		difficulty: "Easy",
		topics: ["Two Pointers"],
		companies: ["LinkedIn", "Twitter", "Microsoft"],
		order: 46,
	},
	{
		id: "longest-substring-without-repeating-characters",
		title: "Longest Substring Without Repeating Characters",
		difficulty: "Medium",
		topics: ["Sliding Window"],
		companies: ["Twitter", "Google"],
		order: 47,
	},
	{
		id: "longest-repeating-character-replacement",
		title: "Longest Repeating Character Replacement",
		difficulty: "Medium",
		topics: ["Sliding Window"],
		companies: ["LinkedIn", "Yahoo", "Apple", "Meta"],
		order: 48,
	},
	{
		id: "permutation-in-string",
		title: "Permutation in String",
		difficulty: "Medium",
		topics: ["Sliding Window"],
		companies: ["Yahoo", "LinkedIn", "Bloomberg"],
		order: 49,
	},
	{
		id: "minimum-window-substring",
		title: "Minimum Window Substring",
		difficulty: "Hard",
		topics: ["Sliding Window"],
		companies: ["Pinterest", "Two Sigma"],
		order: 50,
	},
	{
		id: "sliding-window-maximum",
		title: "Sliding Window Maximum",
		difficulty: "Hard",
		topics: ["Sliding Window"],
		companies: ["Visa", "LinkedIn"],
		order: 51,
	},
	{
		id: "minimum-size-subarray-sum",
		title: "Minimum Size Subarray Sum",
		difficulty: "Medium",
		topics: ["Sliding Window"],
		companies: ["Two Sigma", "Bloomberg", "Microsoft"],
		order: 52,
	},
	{
		id: "fruit-into-baskets",
		title: "Fruit Into Baskets",
		difficulty: "Medium",
		topics: ["Sliding Window"],
		companies: ["Apple", "Adobe"],
		order: 53,
	},
	{
		id: "max-consecutive-ones-iii",
		title: "Max Consecutive Ones III",
		difficulty: "Medium",
		topics: ["Sliding Window"],
		companies: ["Airbnb", "Amazon", "ByteDance"],
		order: 54,
	},
	{
		id: "find-all-anagrams-in-a-string",
		title: "Find All Anagrams in a String",
		difficulty: "Medium",
		topics: ["Sliding Window"],
		companies: ["Meta", "Two Sigma"],
		order: 55,
	},
	{
		id: "longest-substring-with-at-most-two-distinct-characters",
		title: "Longest Substring with At Most Two Distinct Characters",
		difficulty: "Medium",
		topics: ["Sliding Window"],
		companies: ["Pinterest", "Adobe", "Netflix"],
		order: 56,
	},
	{
		id: "longest-substring-with-at-most-k-distinct-characters",
		title: "Longest Substring with At Most K Distinct Characters",
		difficulty: "Medium",
		topics: ["Sliding Window"],
		companies: ["Yahoo", "Adobe", "Cisco", "Google"],
		order: 57,
	},
	{
		id: "maximum-average-subarray-i",
		title: "Maximum Average Subarray I",
		difficulty: "Easy",
		topics: ["Sliding Window"],
		companies: ["Meta", "Microsoft", "Google"],
		order: 58,
	},
	{
		id: "subarrays-with-k-different-integers",
		title: "Subarrays with K Different Integers",
		difficulty: "Hard",
		topics: ["Sliding Window"],
		companies: ["Meta", "Uber"],
		order: 59,
	},
	{
		id: "grumpy-bookstore-owner",
		title: "Grumpy Bookstore Owner",
		difficulty: "Medium",
		topics: ["Sliding Window"],
		companies: ["Bloomberg", "Salesforce", "Two Sigma"],
		order: 60,
	},
	{
		id: "frequency-of-the-most-frequent-element",
		title: "Frequency of the Most Frequent Element",
		difficulty: "Medium",
		topics: ["Sliding Window"],
		companies: ["Yahoo", "Microsoft", "Spotify"],
		order: 61,
	},
	{
		id: "valid-parentheses",
		title: "Valid Parentheses",
		difficulty: "Easy",
		topics: ["Stack"],
		companies: ["Amazon", "Bloomberg", "Visa"],
		order: 62,
		videoId: "xty7fr-k0TU",
	},
	{
		id: "min-stack",
		title: "Min Stack",
		difficulty: "Medium",
		topics: ["Stack"],
		companies: ["Oracle", "Uber"],
		order: 63,
	},
	{
		id: "evaluate-reverse-polish-notation",
		title: "Evaluate Reverse Polish Notation",
		difficulty: "Medium",
		topics: ["Stack"],
		companies: ["Microsoft", "Bloomberg"],
		order: 64,
	},
	{
		id: "generate-parentheses",
		title: "Generate Parentheses",
		difficulty: "Medium",
		topics: ["Stack"],
		companies: ["ByteDance", "Amazon"],
		order: 65,
	},
	{
		id: "daily-temperatures",
		title: "Daily Temperatures",
		difficulty: "Medium",
		topics: ["Stack"],
		companies: ["Google", "Microsoft", "LinkedIn"],
		order: 66,
	},
	{
		id: "car-fleet",
		title: "Car Fleet",
		difficulty: "Medium",
		topics: ["Stack"],
		companies: ["Amazon", "Salesforce"],
		order: 67,
	},
	{
		id: "largest-rectangle-in-histogram",
		title: "Largest Rectangle in Histogram",
		difficulty: "Hard",
		topics: ["Stack"],
		companies: ["Meta", "Microsoft"],
		order: 68,
	},
	{
		id: "next-greater-element-i",
		title: "Next Greater Element I",
		difficulty: "Easy",
		topics: ["Stack"],
		companies: ["Bloomberg", "eBay"],
		order: 69,
	},
	{
		id: "next-greater-element-ii",
		title: "Next Greater Element II",
		difficulty: "Medium",
		topics: ["Stack"],
		companies: ["Google", "Amazon", "PayPal", "Twitter"],
		order: 70,
	},
	{
		id: "asteroid-collision",
		title: "Asteroid Collision",
		difficulty: "Medium",
		topics: ["Stack"],
		companies: ["Goldman Sachs", "Yahoo", "Bloomberg", "Google"],
		order: 71,
	},
	{
		id: "decode-string",
		title: "Decode String",
		difficulty: "Medium",
		topics: ["Stack"],
		companies: ["eBay", "Atlassian", "DoorDash", "Meta"],
		order: 72,
	},
	{
		id: "remove-all-adjacent-duplicates-in-string",
		title: "Remove All Adjacent Duplicates In String",
		difficulty: "Easy",
		topics: ["Stack"],
		companies: ["PayPal", "Salesforce", "Apple"],
		order: 73,
	},
	{
		id: "simplify-path",
		title: "Simplify Path",
		difficulty: "Medium",
		topics: ["Stack"],
		companies: ["Google", "Netflix"],
		order: 74,
	},
	{
		id: "basic-calculator",
		title: "Basic Calculator",
		difficulty: "Hard",
		topics: ["Stack"],
		companies: ["Amazon", "Google"],
		order: 75,
	},
	{
		id: "online-stock-span",
		title: "Online Stock Span",
		difficulty: "Medium",
		topics: ["Stack"],
		companies: ["LinkedIn", "Microsoft", "Meta", "Apple"],
		order: 76,
	},
	{
		id: "search-a-2d-matrix",
		title: "Search a 2D Matrix",
		difficulty: "Medium",
		topics: ["Binary Search"],
		companies: ["Cisco", "Twitter"],
		order: 77,
		videoId: "ZfFl4torNg4",
	},
	{
		id: "binary-search",
		title: "Binary Search",
		difficulty: "Easy",
		topics: ["Binary Search"],
		companies: ["Salesforce", "Pinterest", "Google", "Netflix"],
		order: 78,
	},
	{
		id: "search-in-rotated-sorted-array",
		title: "Search in Rotated Sorted Array",
		difficulty: "Medium",
		topics: ["Binary Search"],
		companies: ["Oracle", "Spotify"],
		order: 79,
	},
	{
		id: "search-in-rotated-sorted-array-ii",
		title: "Search in Rotated Sorted Array II",
		difficulty: "Medium",
		topics: ["Binary Search"],
		companies: ["Salesforce", "Meta"],
		order: 80,
	},
	{
		id: "find-minimum-in-rotated-sorted-array",
		title: "Find Minimum in Rotated Sorted Array",
		difficulty: "Medium",
		topics: ["Binary Search"],
		companies: ["Cisco", "Atlassian", "LinkedIn", "Uber"],
		order: 81,
	},
	{
		id: "find-minimum-in-rotated-sorted-array-ii",
		title: "Find Minimum in Rotated Sorted Array II",
		difficulty: "Hard",
		topics: ["Binary Search"],
		companies: ["Snap", "Apple", "Bloomberg"],
		order: 82,
	},
	{
		id: "time-based-key-value-store",
		title: "Time Based Key-Value Store",
		difficulty: "Medium",
		topics: ["Binary Search"],
		companies: ["Visa", "Microsoft", "eBay", "Two Sigma"],
		order: 83,
	},
	{
		id: "median-of-two-sorted-arrays",
		title: "Median of Two Sorted Arrays",
		difficulty: "Hard",
		topics: ["Binary Search"],
		companies: ["Two Sigma", "Apple"],
		order: 84,
	},
	{
		id: "koko-eating-bananas",
		title: "Koko Eating Bananas",
		difficulty: "Medium",
		topics: ["Binary Search"],
		companies: ["Uber", "ByteDance", "Goldman Sachs"],
		order: 85,
	},
	{
		id: "capacity-to-ship-packages-within-d-days",
		title: "Capacity To Ship Packages Within D Days",
		difficulty: "Medium",
		topics: ["Binary Search"],
		companies: ["Pinterest", "Visa", "Amazon"],
		order: 86,
	},
	{
		id: "split-array-largest-sum",
		title: "Split Array Largest Sum",
		difficulty: "Hard",
		topics: ["Binary Search"],
		companies: ["Goldman Sachs", "Meta"],
		order: 87,
	},
	{
		id: "find-peak-element",
		title: "Find Peak Element",
		difficulty: "Medium",
		topics: ["Binary Search"],
		companies: ["Microsoft", "Twitter", "Apple", "Bloomberg"],
		order: 88,
	},
	{
		id: "search-insert-position",
		title: "Search Insert Position",
		difficulty: "Easy",
		topics: ["Binary Search"],
		companies: ["Amazon", "Walmart Labs", "Meta", "Bloomberg"],
		order: 89,
	},
	{
		id: "first-bad-version",
		title: "First Bad Version",
		difficulty: "Easy",
		topics: ["Binary Search"],
		companies: ["Google", "Meta", "Uber", "Microsoft"],
		order: 90,
	},
	{
		id: "find-first-and-last-position-of-element-in-sorted-array",
		title: "Find First and Last Position of Element in Sorted Array",
		difficulty: "Medium",
		topics: ["Binary Search"],
		companies: ["eBay", "Snap", "Visa"],
		order: 91,
	},
	{
		id: "reverse-linked-list",
		title: "Reverse Linked List",
		difficulty: "Easy",
		topics: ["Linked List"],
		companies: ["Visa", "Amazon", "Walmart Labs"],
		order: 92,
	},
	{
		id: "merge-two-sorted-lists",
		title: "Merge Two Sorted Lists",
		difficulty: "Easy",
		topics: ["Linked List"],
		companies: ["Meta", "Apple", "PayPal", "LinkedIn"],
		order: 93,
	},
	{
		id: "linked-list-cycle",
		title: "Linked List Cycle",
		difficulty: "Easy",
		topics: ["Linked List"],
		companies: ["Snap", "Microsoft", "ByteDance", "Amazon"],
		order: 94,
	},
	{
		id: "linked-list-cycle-ii",
		title: "Linked List Cycle II",
		difficulty: "Medium",
		topics: ["Linked List"],
		companies: ["Google", "Microsoft", "Snap", "Amazon"],
		order: 95,
	},
	{
		id: "reorder-list",
		title: "Reorder List",
		difficulty: "Medium",
		topics: ["Linked List"],
		companies: ["Pinterest", "LinkedIn"],
		order: 96,
	},
	{
		id: "remove-nth-node-from-end-of-list",
		title: "Remove Nth Node From End of List",
		difficulty: "Medium",
		topics: ["Linked List"],
		companies: ["Amazon", "Airbnb"],
		order: 97,
	},
	{
		id: "copy-list-with-random-pointer",
		title: "Copy List with Random Pointer",
		difficulty: "Medium",
		topics: ["Linked List"],
		companies: ["PayPal", "Cisco", "ByteDance"],
		order: 98,
	},
	{
		id: "add-two-numbers",
		title: "Add Two Numbers",
		difficulty: "Medium",
		topics: ["Linked List"],
		companies: ["Bloomberg", "LinkedIn"],
		order: 99,
	},
	{
		id: "merge-k-sorted-lists",
		title: "Merge k Sorted Lists",
		difficulty: "Hard",
		topics: ["Linked List"],
		companies: ["Apple", "eBay", "LinkedIn"],
		order: 100,
	},
	{
		id: "lru-cache",
		title: "LRU Cache",
		difficulty: "Medium",
		topics: ["Linked List"],
		companies: ["Uber", "Google", "Amazon"],
		order: 101,
	},
	{
		id: "lfu-cache",
		title: "LFU Cache",
		difficulty: "Hard",
		topics: ["Linked List"],
		companies: ["Uber", "Bloomberg", "Spotify", "Yahoo"],
		order: 102,
	},
	{
		id: "palindrome-linked-list",
		title: "Palindrome Linked List",
		difficulty: "Easy",
		topics: ["Linked List"],
		companies: ["Walmart Labs", "Apple", "PayPal"],
		order: 103,
	},
	{
		id: "odd-even-linked-list",
		title: "Odd Even Linked List",
		difficulty: "Medium",
		topics: ["Linked List"],
		companies: ["Snap", "Meta", "Two Sigma"],
		order: 104,
	},
	{
		id: "swap-nodes-in-pairs",
		title: "Swap Nodes in Pairs",
		difficulty: "Medium",
		topics: ["Linked List"],
		companies: ["Google", "Visa", "ByteDance", "Goldman Sachs"],
		order: 105,
	},
	{
		id: "rotate-list",
		title: "Rotate List",
		difficulty: "Medium",
		topics: ["Linked List"],
		companies: ["Bloomberg", "Adobe", "Uber"],
		order: 106,
	},
	{
		id: "maximum-depth-of-binary-tree",
		title: "Maximum Depth of Binary Tree",
		difficulty: "Easy",
		topics: ["Trees"],
		companies: ["Microsoft", "Visa"],
		order: 107,
	},
	{
		id: "same-tree",
		title: "Same Tree",
		difficulty: "Easy",
		topics: ["Trees"],
		companies: ["Uber", "Amazon", "Oracle", "Bloomberg"],
		order: 108,
	},
	{
		id: "invert-binary-tree",
		title: "Invert Binary Tree",
		difficulty: "Easy",
		topics: ["Trees"],
		companies: ["Apple", "Cisco", "Uber", "Twitter"],
		order: 109,
	},
	{
		id: "subtree-of-another-tree",
		title: "Subtree of Another Tree",
		difficulty: "Easy",
		topics: ["Trees"],
		companies: ["Adobe", "Snap"],
		order: 110,
	},
	{
		id: "binary-tree-level-order-traversal",
		title: "Binary Tree Level Order Traversal",
		difficulty: "Medium",
		topics: ["Trees"],
		companies: ["Amazon", "Microsoft", "Salesforce", "PayPal"],
		order: 111,
	},
	{
		id: "binary-tree-zigzag-level-order-traversal",
		title: "Binary Tree Zigzag Level Order Traversal",
		difficulty: "Medium",
		topics: ["Trees"],
		companies: ["eBay", "Two Sigma", "Goldman Sachs", "Amazon"],
		order: 112,
	},
	{
		id: "binary-tree-right-side-view",
		title: "Binary Tree Right Side View",
		difficulty: "Medium",
		topics: ["Trees"],
		companies: ["Salesforce", "Pinterest", "Google"],
		order: 113,
	},
	{
		id: "count-good-nodes-in-binary-tree",
		title: "Count Good Nodes in Binary Tree",
		difficulty: "Medium",
		topics: ["Trees"],
		companies: ["Spotify", "Meta"],
		order: 114,
	},
	{
		id: "validate-binary-search-tree",
		title: "Validate Binary Search Tree",
		difficulty: "Medium",
		topics: ["Trees"],
		companies: ["Microsoft", "Amazon", "Uber", "Google"],
		order: 115,
	},
	{
		id: "kth-smallest-element-in-a-bst",
		title: "Kth Smallest Element in a BST",
		difficulty: "Medium",
		topics: ["Trees"],
		companies: ["Pinterest", "Amazon"],
		order: 116,
	},
	{
		id: "construct-binary-tree-from-preorder-and-inorder-traversal",
		title: "Construct Binary Tree from Preorder and Inorder Traversal",
		difficulty: "Medium",
		topics: ["Trees"],
		companies: ["Meta", "ByteDance", "Pinterest"],
		order: 117,
	},
	{
		id: "binary-tree-maximum-path-sum",
		title: "Binary Tree Maximum Path Sum",
		difficulty: "Hard",
		topics: ["Trees"],
		companies: ["Meta", "Pinterest"],
		order: 118,
	},
	{
		id: "serialize-and-deserialize-binary-tree",
		title: "Serialize and Deserialize Binary Tree",
		difficulty: "Hard",
		topics: ["Trees"],
		companies: ["Yahoo", "Microsoft", "PayPal", "Snap"],
		order: 119,
	},
	{
		id: "lowest-common-ancestor-of-a-binary-search-tree",
		title: "Lowest Common Ancestor of a Binary Search Tree",
		difficulty: "Medium",
		topics: ["Trees"],
		companies: ["Salesforce", "Amazon", "Yahoo"],
		order: 120,
	},
	{
		id: "lowest-common-ancestor-of-a-binary-tree",
		title: "Lowest Common Ancestor of a Binary Tree",
		difficulty: "Medium",
		topics: ["Trees"],
		companies: ["Airbnb", "DoorDash"],
		order: 121,
	},
	{
		id: "balanced-binary-tree",
		title: "Balanced Binary Tree",
		difficulty: "Easy",
		topics: ["Trees"],
		companies: ["Meta", "Uber", "LinkedIn"],
		order: 122,
	},
	{
		id: "diameter-of-binary-tree",
		title: "Diameter of Binary Tree",
		difficulty: "Easy",
		topics: ["Trees"],
		companies: ["Visa", "Uber"],
		order: 123,
	},
	{
		id: "symmetric-tree",
		title: "Symmetric Tree",
		difficulty: "Easy",
		topics: ["Trees"],
		companies: ["Amazon", "Salesforce", "Microsoft", "Apple"],
		order: 124,
	},
	{
		id: "path-sum",
		title: "Path Sum",
		difficulty: "Easy",
		topics: ["Trees"],
		companies: ["Amazon", "Uber", "Goldman Sachs", "DoorDash"],
		order: 125,
	},
	{
		id: "path-sum-ii",
		title: "Path Sum II",
		difficulty: "Medium",
		topics: ["Trees"],
		companies: ["Apple", "Bloomberg", "LinkedIn"],
		order: 126,
	},
	{
		id: "flatten-binary-tree-to-linked-list",
		title: "Flatten Binary Tree to Linked List",
		difficulty: "Medium",
		topics: ["Trees"],
		companies: ["Adobe", "Google", "Two Sigma"],
		order: 127,
	},
	{
		id: "binary-tree-inorder-traversal",
		title: "Binary Tree Inorder Traversal",
		difficulty: "Easy",
		topics: ["Trees"],
		companies: ["Amazon", "Snap", "Google", "Twitter"],
		order: 128,
	},
	{
		id: "binary-tree-preorder-traversal",
		title: "Binary Tree Preorder Traversal",
		difficulty: "Easy",
		topics: ["Trees"],
		companies: ["Netflix", "Uber", "Salesforce"],
		order: 129,
	},
	{
		id: "binary-tree-postorder-traversal",
		title: "Binary Tree Postorder Traversal",
		difficulty: "Easy",
		topics: ["Trees"],
		companies: ["Uber", "Bloomberg"],
		order: 130,
	},
	{
		id: "convert-sorted-array-to-binary-search-tree",
		title: "Convert Sorted Array to Binary Search Tree",
		difficulty: "Easy",
		topics: ["Trees"],
		companies: ["Amazon", "Yahoo", "Google", "Salesforce"],
		order: 131,
	},
	{
		id: "implement-trie",
		title: "Implement Trie (Prefix Tree)",
		difficulty: "Medium",
		topics: ["Tries"],
		companies: ["Microsoft", "Atlassian", "DoorDash"],
		order: 132,
	},
	{
		id: "design-add-and-search-words-data-structure",
		title: "Design Add and Search Words Data Structure",
		difficulty: "Medium",
		topics: ["Tries"],
		companies: ["eBay", "DoorDash", "Netflix"],
		order: 133,
	},
	{
		id: "word-search-ii",
		title: "Word Search II",
		difficulty: "Hard",
		topics: ["Tries"],
		companies: ["Oracle", "Google", "Two Sigma"],
		order: 134,
	},
	{
		id: "replace-words",
		title: "Replace Words",
		difficulty: "Medium",
		topics: ["Tries"],
		companies: ["Salesforce", "Amazon"],
		order: 135,
	},
	{
		id: "longest-word-in-dictionary",
		title: "Longest Word in Dictionary",
		difficulty: "Medium",
		topics: ["Tries"],
		companies: ["Meta", "Visa"],
		order: 136,
	},
	{
		id: "kth-largest-element-in-an-array",
		title: "Kth Largest Element in an Array",
		difficulty: "Medium",
		topics: ["Heap / Priority Queue"],
		companies: ["Yahoo", "Meta"],
		order: 137,
	},
	{
		id: "kth-largest-element-in-a-stream",
		title: "Kth Largest Element in a Stream",
		difficulty: "Easy",
		topics: ["Heap / Priority Queue"],
		companies: ["Bloomberg", "Amazon", "Apple"],
		order: 138,
	},
	{
		id: "last-stone-weight",
		title: "Last Stone Weight",
		difficulty: "Easy",
		topics: ["Heap / Priority Queue"],
		companies: ["Meta", "LinkedIn", "Visa"],
		order: 139,
	},
	{
		id: "k-closest-points-to-origin",
		title: "K Closest Points to Origin",
		difficulty: "Medium",
		topics: ["Heap / Priority Queue"],
		companies: ["Google", "Amazon", "Uber"],
		order: 140,
	},
	{
		id: "task-scheduler",
		title: "Task Scheduler",
		difficulty: "Medium",
		topics: ["Heap / Priority Queue"],
		companies: ["Visa", "Meta", "Amazon"],
		order: 141,
	},
	{
		id: "design-twitter",
		title: "Design Twitter",
		difficulty: "Medium",
		topics: ["Heap / Priority Queue"],
		companies: ["Spotify", "Walmart Labs", "Netflix", "eBay"],
		order: 142,
	},
	{
		id: "find-median-from-data-stream",
		title: "Find Median from Data Stream",
		difficulty: "Hard",
		topics: ["Heap / Priority Queue"],
		companies: ["Uber", "Atlassian", "LinkedIn", "Bloomberg"],
		order: 143,
	},
	{
		id: "top-k-frequent-words",
		title: "Top K Frequent Words",
		difficulty: "Medium",
		topics: ["Heap / Priority Queue"],
		companies: ["Uber", "Amazon", "Google", "Goldman Sachs"],
		order: 144,
	},
	{
		id: "reorganize-string",
		title: "Reorganize String",
		difficulty: "Medium",
		topics: ["Heap / Priority Queue"],
		companies: ["Uber", "Yahoo"],
		order: 145,
	},
	{
		id: "ugly-number-ii",
		title: "Ugly Number II",
		difficulty: "Medium",
		topics: ["Heap / Priority Queue"],
		companies: ["ByteDance", "LinkedIn", "Microsoft"],
		order: 146,
	},
	{
		id: "subsets",
		title: "Subsets",
		difficulty: "Medium",
		topics: ["Backtracking"],
		companies: ["Adobe", "PayPal", "Cisco"],
		order: 147,
	},
	{
		id: "subsets-ii",
		title: "Subsets II",
		difficulty: "Medium",
		topics: ["Backtracking"],
		companies: ["Apple", "Meta"],
		order: 148,
	},
	{
		id: "combination-sum",
		title: "Combination Sum",
		difficulty: "Medium",
		topics: ["Backtracking"],
		companies: ["Salesforce", "ByteDance", "Netflix"],
		order: 149,
	},
	{
		id: "combination-sum-ii",
		title: "Combination Sum II",
		difficulty: "Medium",
		topics: ["Backtracking"],
		companies: ["Cisco", "Spotify", "Pinterest"],
		order: 150,
	},
	{
		id: "permutations",
		title: "Permutations",
		difficulty: "Medium",
		topics: ["Backtracking"],
		companies: ["Goldman Sachs", "Meta", "Microsoft"],
		order: 151,
	},
	{
		id: "permutations-ii",
		title: "Permutations II",
		difficulty: "Medium",
		topics: ["Backtracking"],
		companies: ["Google", "DoorDash", "Pinterest"],
		order: 152,
	},
	{
		id: "word-search",
		title: "Word Search",
		difficulty: "Medium",
		topics: ["Backtracking", "Matrix"],
		companies: ["Bloomberg", "Netflix"],
		order: 153,
	},
	{
		id: "palindrome-partitioning",
		title: "Palindrome Partitioning",
		difficulty: "Medium",
		topics: ["Backtracking"],
		companies: ["LinkedIn", "Google", "Bloomberg"],
		order: 154,
	},
	{
		id: "letter-combinations-of-a-phone-number",
		title: "Letter Combinations of a Phone Number",
		difficulty: "Medium",
		topics: ["Backtracking"],
		companies: ["Netflix", "Adobe", "Meta", "Google"],
		order: 155,
	},
	{
		id: "n-queens",
		title: "N-Queens",
		difficulty: "Hard",
		topics: ["Backtracking"],
		companies: ["Meta", "Goldman Sachs", "ByteDance"],
		order: 156,
	},
	{
		id: "n-queens-ii",
		title: "N-Queens II",
		difficulty: "Hard",
		topics: ["Backtracking"],
		companies: ["Microsoft", "ByteDance", "LinkedIn", "Amazon"],
		order: 157,
	},
	{
		id: "sudoku-solver",
		title: "Sudoku Solver",
		difficulty: "Hard",
		topics: ["Backtracking"],
		companies: ["Yahoo", "Google"],
		order: 158,
	},
	{
		id: "combinations",
		title: "Combinations",
		difficulty: "Medium",
		topics: ["Backtracking"],
		companies: ["ByteDance", "Yahoo"],
		order: 159,
	},
	{
		id: "restore-ip-addresses",
		title: "Restore IP Addresses",
		difficulty: "Medium",
		topics: ["Backtracking"],
		companies: ["Meta", "ByteDance", "Apple"],
		order: 160,
	},
	{
		id: "unique-paths-iii",
		title: "Unique Paths III",
		difficulty: "Hard",
		topics: ["Backtracking"],
		companies: ["Meta", "Google"],
		order: 161,
	},
	{
		id: "number-of-islands",
		title: "Number of Islands",
		difficulty: "Medium",
		topics: ["Graphs"],
		companies: ["Uber", "Cisco"],
		order: 162,
	},
	{
		id: "max-area-of-island",
		title: "Max Area of Island",
		difficulty: "Medium",
		topics: ["Graphs"],
		companies: ["Uber", "Salesforce", "PayPal"],
		order: 163,
	},
	{
		id: "clone-graph",
		title: "Clone Graph",
		difficulty: "Medium",
		topics: ["Graphs"],
		companies: ["Apple", "Uber"],
		order: 164,
	},
	{
		id: "walls-and-gates",
		title: "Walls and Gates",
		difficulty: "Medium",
		topics: ["Graphs"],
		companies: ["Adobe", "Amazon", "Uber", "Walmart Labs"],
		order: 165,
	},
	{
		id: "rotting-oranges",
		title: "Rotting Oranges",
		difficulty: "Medium",
		topics: ["Graphs"],
		companies: ["Apple", "Oracle", "DoorDash"],
		order: 166,
	},
	{
		id: "pacific-atlantic-water-flow",
		title: "Pacific Atlantic Water Flow",
		difficulty: "Medium",
		topics: ["Graphs"],
		companies: ["Apple", "Microsoft"],
		order: 167,
	},
	{
		id: "surrounded-regions",
		title: "Surrounded Regions",
		difficulty: "Medium",
		topics: ["Graphs"],
		companies: ["Pinterest", "Snap"],
		order: 168,
	},
	{
		id: "course-schedule",
		title: "Course Schedule",
		difficulty: "Medium",
		topics: ["Graphs"],
		companies: ["Amazon", "Spotify", "Bloomberg", "Walmart Labs"],
		order: 169,
	},
	{
		id: "course-schedule-ii",
		title: "Course Schedule II",
		difficulty: "Medium",
		topics: ["Graphs"],
		companies: ["Google", "Amazon", "DoorDash"],
		order: 170,
	},
	{
		id: "graph-valid-tree",
		title: "Graph Valid Tree",
		difficulty: "Medium",
		topics: ["Graphs"],
		companies: ["Adobe", "Google"],
		order: 171,
	},
	{
		id: "number-of-connected-components-in-an-undirected-graph",
		title: "Number of Connected Components in an Undirected Graph",
		difficulty: "Medium",
		topics: ["Graphs"],
		companies: ["LinkedIn", "Uber", "Meta"],
		order: 172,
	},
	{
		id: "redundant-connection",
		title: "Redundant Connection",
		difficulty: "Medium",
		topics: ["Graphs"],
		companies: ["LinkedIn", "Apple", "Spotify"],
		order: 173,
	},
	{
		id: "word-ladder",
		title: "Word Ladder",
		difficulty: "Hard",
		topics: ["Graphs"],
		companies: ["Bloomberg", "Google", "Meta", "Uber"],
		order: 174,
	},
	{
		id: "word-ladder-ii",
		title: "Word Ladder II",
		difficulty: "Hard",
		topics: ["Graphs"],
		companies: ["Netflix", "Two Sigma"],
		order: 175,
	},
	{
		id: "reconstruct-itinerary",
		title: "Reconstruct Itinerary",
		difficulty: "Hard",
		topics: ["Graphs"],
		companies: ["LinkedIn", "Bloomberg", "Snap", "Apple"],
		order: 176,
	},
	{
		id: "evaluate-division",
		title: "Evaluate Division",
		difficulty: "Medium",
		topics: ["Graphs"],
		companies: ["Bloomberg", "Microsoft", "Apple"],
		order: 177,
	},
	{
		id: "is-graph-bipartite",
		title: "Is Graph Bipartite",
		difficulty: "Medium",
		topics: ["Graphs"],
		companies: ["Apple", "Yahoo"],
		order: 178,
	},
	{
		id: "minimum-height-trees",
		title: "Minimum Height Trees",
		difficulty: "Medium",
		topics: ["Graphs"],
		companies: ["PayPal", "Walmart Labs", "Google", "Bloomberg"],
		order: 179,
	},
	{
		id: "all-paths-from-source-to-target",
		title: "All Paths From Source to Target",
		difficulty: "Medium",
		topics: ["Graphs"],
		companies: ["Amazon", "Uber", "Meta"],
		order: 180,
	},
	{
		id: "flood-fill",
		title: "Flood Fill",
		difficulty: "Easy",
		topics: ["Graphs"],
		companies: ["Airbnb", "Uber"],
		order: 181,
	},
	{
		id: "network-delay-time",
		title: "Network Delay Time",
		difficulty: "Medium",
		topics: ["Advanced Graphs"],
		companies: ["Spotify", "Google", "Walmart Labs", "Bloomberg"],
		order: 182,
	},
	{
		id: "cheapest-flights-within-k-stops",
		title: "Cheapest Flights Within K Stops",
		difficulty: "Medium",
		topics: ["Advanced Graphs"],
		companies: ["Microsoft", "Goldman Sachs", "Oracle", "Snap"],
		order: 183,
	},
	{
		id: "swim-in-rising-water",
		title: "Swim in Rising Water",
		difficulty: "Hard",
		topics: ["Advanced Graphs"],
		companies: ["Google", "Bloomberg", "LinkedIn", "Two Sigma"],
		order: 184,
	},
	{
		id: "alien-dictionary",
		title: "Alien Dictionary",
		difficulty: "Hard",
		topics: ["Advanced Graphs"],
		companies: ["Apple", "Amazon"],
		order: 185,
	},
	{
		id: "min-cost-to-connect-all-points",
		title: "Min Cost to Connect All Points",
		difficulty: "Medium",
		topics: ["Advanced Graphs"],
		companies: ["PayPal", "Bloomberg", "Twitter"],
		order: 186,
	},
	{
		id: "path-with-maximum-probability",
		title: "Path with Maximum Probability",
		difficulty: "Medium",
		topics: ["Advanced Graphs"],
		companies: ["Visa", "LinkedIn", "Airbnb", "Uber"],
		order: 187,
	},
	{
		id: "critical-connections-in-a-network",
		title: "Critical Connections in a Network",
		difficulty: "Hard",
		topics: ["Advanced Graphs"],
		companies: ["Meta", "eBay", "Visa"],
		order: 188,
	},
	{
		id: "number-of-provinces",
		title: "Number of Provinces",
		difficulty: "Medium",
		topics: ["Advanced Graphs"],
		companies: ["Yahoo", "Google", "Amazon", "Adobe"],
		order: 189,
	},
	{
		id: "accounts-merge",
		title: "Accounts Merge",
		difficulty: "Medium",
		topics: ["Advanced Graphs"],
		companies: ["Bloomberg", "Airbnb"],
		order: 190,
	},
	{
		id: "find-the-city-with-the-smallest-number-of-neighbors-at-a-threshold-distance",
		title: "Find the City With the Smallest Number of Neighbors at a Threshold Distance",
		difficulty: "Medium",
		topics: ["Advanced Graphs"],
		companies: ["Google", "Airbnb", "Apple", "Bloomberg"],
		order: 191,
	},
	{
		id: "climbing-stairs",
		title: "Climbing Stairs",
		difficulty: "Easy",
		topics: ["1-D Dynamic Programming"],
		companies: ["DoorDash", "Twitter"],
		order: 192,
	},
	{
		id: "house-robber",
		title: "House Robber",
		difficulty: "Medium",
		topics: ["1-D Dynamic Programming"],
		companies: ["Goldman Sachs", "Amazon", "Google"],
		order: 193,
	},
	{
		id: "house-robber-ii",
		title: "House Robber II",
		difficulty: "Medium",
		topics: ["1-D Dynamic Programming"],
		companies: ["Meta", "Cisco", "eBay"],
		order: 194,
	},
	{
		id: "longest-palindromic-substring",
		title: "Longest Palindromic Substring",
		difficulty: "Medium",
		topics: ["1-D Dynamic Programming"],
		companies: ["Pinterest", "Google", "Snap", "Amazon"],
		order: 195,
	},
	{
		id: "palindromic-substrings",
		title: "Palindromic Substrings",
		difficulty: "Medium",
		topics: ["1-D Dynamic Programming"],
		companies: ["Bloomberg", "Salesforce", "Microsoft"],
		order: 196,
	},
	{
		id: "decode-ways",
		title: "Decode Ways",
		difficulty: "Medium",
		topics: ["1-D Dynamic Programming"],
		companies: ["Yahoo", "Meta", "Google"],
		order: 197,
	},
	{
		id: "coin-change",
		title: "Coin Change",
		difficulty: "Medium",
		topics: ["1-D Dynamic Programming"],
		companies: ["Apple", "Microsoft", "Snap"],
		order: 198,
	},
	{
		id: "coin-change-ii",
		title: "Coin Change II",
		difficulty: "Medium",
		topics: ["1-D Dynamic Programming"],
		companies: ["Yahoo", "Netflix", "Goldman Sachs"],
		order: 199,
	},
	{
		id: "maximum-product-subarray",
		title: "Maximum Product Subarray",
		difficulty: "Medium",
		topics: ["1-D Dynamic Programming"],
		companies: ["eBay", "Adobe"],
		order: 200,
	},
	{
		id: "word-break",
		title: "Word Break",
		difficulty: "Medium",
		topics: ["1-D Dynamic Programming"],
		companies: ["Amazon", "Adobe", "Microsoft"],
		order: 201,
	},
	{
		id: "longest-increasing-subsequence",
		title: "Longest Increasing Subsequence",
		difficulty: "Medium",
		topics: ["1-D Dynamic Programming"],
		companies: ["LinkedIn", "Spotify", "Apple", "Google"],
		order: 202,
	},
	{
		id: "partition-equal-subset-sum",
		title: "Partition Equal Subset Sum",
		difficulty: "Medium",
		topics: ["1-D Dynamic Programming"],
		companies: ["Uber", "Salesforce"],
		order: 203,
	},
	{
		id: "combination-sum-iv",
		title: "Combination Sum IV",
		difficulty: "Medium",
		topics: ["1-D Dynamic Programming"],
		companies: ["Apple", "Microsoft", "LinkedIn", "ByteDance"],
		order: 204,
	},
	{
		id: "perfect-squares",
		title: "Perfect Squares",
		difficulty: "Medium",
		topics: ["1-D Dynamic Programming"],
		companies: ["LinkedIn", "Meta"],
		order: 205,
	},
	{
		id: "integer-break",
		title: "Integer Break",
		difficulty: "Medium",
		topics: ["1-D Dynamic Programming"],
		companies: ["LinkedIn", "Twitter", "ByteDance"],
		order: 206,
	},
	{
		id: "delete-and-earn",
		title: "Delete and Earn",
		difficulty: "Medium",
		topics: ["1-D Dynamic Programming"],
		companies: ["Salesforce", "Amazon", "Bloomberg", "Pinterest"],
		order: 207,
	},
	{
		id: "domino-and-tromino-tiling",
		title: "Domino and Tromino Tiling",
		difficulty: "Medium",
		topics: ["1-D Dynamic Programming"],
		companies: ["Amazon", "Bloomberg", "Google"],
		order: 208,
	},
	{
		id: "min-cost-climbing-stairs",
		title: "Min Cost Climbing Stairs",
		difficulty: "Easy",
		topics: ["1-D Dynamic Programming"],
		companies: ["LinkedIn", "Google", "ByteDance"],
		order: 209,
	},
	{
		id: "fibonacci-number",
		title: "Fibonacci Number",
		difficulty: "Easy",
		topics: ["1-D Dynamic Programming"],
		companies: ["Microsoft", "Oracle", "Walmart Labs", "Adobe"],
		order: 210,
	},
	{
		id: "jump-game-ii",
		title: "Jump Game II",
		difficulty: "Medium",
		topics: ["1-D Dynamic Programming"],
		companies: ["Spotify", "Amazon", "DoorDash"],
		order: 211,
	},
	{
		id: "unique-paths",
		title: "Unique Paths",
		difficulty: "Medium",
		topics: ["2-D Dynamic Programming"],
		companies: ["Netflix", "Cisco", "Adobe", "Amazon"],
		order: 212,
	},
	{
		id: "unique-paths-ii",
		title: "Unique Paths II",
		difficulty: "Medium",
		topics: ["2-D Dynamic Programming"],
		companies: ["Microsoft", "Two Sigma", "Airbnb"],
		order: 213,
	},
	{
		id: "minimum-path-sum",
		title: "Minimum Path Sum",
		difficulty: "Medium",
		topics: ["2-D Dynamic Programming"],
		companies: ["Google", "Goldman Sachs", "Twitter", "Bloomberg"],
		order: 214,
	},
	{
		id: "longest-common-subsequence",
		title: "Longest Common Subsequence",
		difficulty: "Medium",
		topics: ["2-D Dynamic Programming"],
		companies: ["Microsoft", "Netflix"],
		order: 215,
	},
	{
		id: "best-time-to-buy-and-sell-stock-with-cooldown",
		title: "Best Time to Buy and Sell Stock with Cooldown",
		difficulty: "Medium",
		topics: ["2-D Dynamic Programming"],
		companies: ["Uber", "Netflix"],
		order: 216,
	},
	{
		id: "best-time-to-buy-and-sell-stock-iii",
		title: "Best Time to Buy and Sell Stock III",
		difficulty: "Hard",
		topics: ["2-D Dynamic Programming"],
		companies: ["Netflix", "Walmart Labs"],
		order: 217,
	},
	{
		id: "best-time-to-buy-and-sell-stock-iv",
		title: "Best Time to Buy and Sell Stock IV",
		difficulty: "Hard",
		topics: ["2-D Dynamic Programming"],
		companies: ["eBay", "Salesforce", "Pinterest"],
		order: 218,
	},
	{
		id: "edit-distance",
		title: "Edit Distance",
		difficulty: "Hard",
		topics: ["2-D Dynamic Programming"],
		companies: ["LinkedIn", "Snap"],
		order: 219,
	},
	{
		id: "interleaving-string",
		title: "Interleaving String",
		difficulty: "Medium",
		topics: ["2-D Dynamic Programming"],
		companies: ["Pinterest", "LinkedIn", "Two Sigma"],
		order: 220,
	},
	{
		id: "distinct-subsequences",
		title: "Distinct Subsequences",
		difficulty: "Hard",
		topics: ["2-D Dynamic Programming"],
		companies: ["Twitter", "DoorDash", "LinkedIn", "Microsoft"],
		order: 221,
	},
	{
		id: "longest-increasing-path-in-a-matrix",
		title: "Longest Increasing Path in a Matrix",
		difficulty: "Hard",
		topics: ["2-D Dynamic Programming"],
		companies: ["Uber", "Oracle"],
		order: 222,
	},
	{
		id: "maximal-square",
		title: "Maximal Square",
		difficulty: "Medium",
		topics: ["2-D Dynamic Programming"],
		companies: ["LinkedIn", "PayPal", "Airbnb"],
		order: 223,
	},
	{
		id: "regular-expression-matching",
		title: "Regular Expression Matching",
		difficulty: "Hard",
		topics: ["2-D Dynamic Programming"],
		companies: ["Airbnb", "Salesforce"],
		order: 224,
	},
	{
		id: "wildcard-matching",
		title: "Wildcard Matching",
		difficulty: "Hard",
		topics: ["2-D Dynamic Programming"],
		companies: ["ByteDance", "Uber", "Salesforce"],
		order: 225,
	},
	{
		id: "target-sum",
		title: "Target Sum",
		difficulty: "Medium",
		topics: ["2-D Dynamic Programming"],
		companies: ["Microsoft", "Snap"],
		order: 226,
	},
	{
		id: "maximum-subarray",
		title: "Maximum Subarray",
		difficulty: "Medium",
		topics: ["Greedy"],
		companies: ["Microsoft", "Airbnb"],
		order: 227,
	},
	{
		id: "jump-game",
		title: "Jump Game",
		difficulty: "Medium",
		topics: ["Greedy"],
		companies: ["Bloomberg", "Microsoft", "PayPal", "Uber"],
		order: 228,
	},
	{
		id: "gas-station",
		title: "Gas Station",
		difficulty: "Medium",
		topics: ["Greedy"],
		companies: ["Salesforce", "Meta", "Bloomberg"],
		order: 229,
	},
	{
		id: "hand-of-straights",
		title: "Hand of Straights",
		difficulty: "Medium",
		topics: ["Greedy"],
		companies: ["Oracle", "Visa", "LinkedIn"],
		order: 230,
	},
	{
		id: "merge-triplets-to-form-target-triplet",
		title: "Merge Triplets to Form Target Triplet",
		difficulty: "Medium",
		topics: ["Greedy"],
		companies: ["Apple", "Pinterest", "Meta", "Visa"],
		order: 231,
	},
	{
		id: "valid-parenthesis-string",
		title: "Valid Parenthesis String",
		difficulty: "Medium",
		topics: ["Greedy"],
		companies: ["Snap", "Walmart Labs", "Bloomberg", "Cisco"],
		order: 232,
	},
	{
		id: "candy",
		title: "Candy",
		difficulty: "Hard",
		topics: ["Greedy"],
		companies: ["Spotify", "Twitter"],
		order: 233,
	},
	{
		id: "lemonade-change",
		title: "Lemonade Change",
		difficulty: "Easy",
		topics: ["Greedy"],
		companies: ["Airbnb", "Bloomberg", "Uber"],
		order: 234,
	},
	{
		id: "assign-cookies",
		title: "Assign Cookies",
		difficulty: "Easy",
		topics: ["Greedy"],
		companies: ["Atlassian", "PayPal"],
		order: 235,
	},
	{
		id: "queue-reconstruction-by-height",
		title: "Queue Reconstruction by Height",
		difficulty: "Medium",
		topics: ["Greedy"],
		companies: ["Meta", "Amazon", "Two Sigma", "Bloomberg"],
		order: 236,
	},
	{
		id: "jump-game-iii",
		title: "Jump Game III",
		difficulty: "Medium",
		topics: ["Greedy"],
		companies: ["LinkedIn", "Microsoft"],
		order: 237,
	},
	{
		id: "non-overlapping-intervals",
		title: "Non-overlapping Intervals",
		difficulty: "Medium",
		topics: ["Greedy"],
		companies: ["Microsoft", "Airbnb", "LinkedIn"],
		order: 238,
	},
	{
		id: "partition-labels",
		title: "Partition Labels",
		difficulty: "Medium",
		topics: ["Greedy"],
		companies: ["LinkedIn", "Salesforce", "Visa", "DoorDash"],
		order: 239,
	},
	{
		id: "minimum-number-of-arrows-to-burst-balloons",
		title: "Minimum Number of Arrows to Burst Balloons",
		difficulty: "Medium",
		topics: ["Greedy"],
		companies: ["Microsoft", "Snap", "ByteDance"],
		order: 240,
	},
	{
		id: "two-city-scheduling",
		title: "Two City Scheduling",
		difficulty: "Medium",
		topics: ["Greedy"],
		companies: ["Uber", "Apple", "Goldman Sachs", "LinkedIn"],
		order: 241,
	},
	{
		id: "merge-intervals",
		title: "Merge Intervals",
		difficulty: "Medium",
		topics: ["Intervals"],
		companies: ["Google", "DoorDash", "ByteDance", "Amazon"],
		order: 242,
	},
	{
		id: "insert-interval",
		title: "Insert Interval",
		difficulty: "Medium",
		topics: ["Intervals"],
		companies: ["Snap", "Meta"],
		order: 243,
	},
	{
		id: "meeting-rooms",
		title: "Meeting Rooms",
		difficulty: "Easy",
		topics: ["Intervals"],
		companies: ["Microsoft", "Walmart Labs", "LinkedIn"],
		order: 244,
	},
	{
		id: "meeting-rooms-ii",
		title: "Meeting Rooms II",
		difficulty: "Medium",
		topics: ["Intervals"],
		companies: ["Uber", "DoorDash", "Amazon"],
		order: 245,
	},
	{
		id: "interval-list-intersections",
		title: "Interval List Intersections",
		difficulty: "Medium",
		topics: ["Intervals"],
		companies: ["Microsoft", "Two Sigma"],
		order: 246,
	},
	{
		id: "my-calendar-i",
		title: "My Calendar I",
		difficulty: "Medium",
		topics: ["Intervals"],
		companies: ["Twitter", "Spotify", "Google", "Adobe"],
		order: 247,
	},
	{
		id: "employee-free-time",
		title: "Employee Free Time",
		difficulty: "Hard",
		topics: ["Intervals"],
		companies: ["Apple", "Uber"],
		order: 248,
	},
	{
		id: "car-pooling",
		title: "Car Pooling",
		difficulty: "Medium",
		topics: ["Intervals"],
		companies: ["Adobe", "Apple", "Twitter"],
		order: 249,
	},
	{
		id: "minimum-interval-to-include-each-query",
		title: "Minimum Interval to Include Each Query",
		difficulty: "Hard",
		topics: ["Intervals"],
		companies: ["Amazon", "Uber", "Airbnb"],
		order: 250,
	},
	{
		id: "remove-covered-intervals",
		title: "Remove Covered Intervals",
		difficulty: "Medium",
		topics: ["Intervals"],
		companies: ["eBay", "Microsoft", "Bloomberg", "Two Sigma"],
		order: 251,
	},
	{
		id: "rotate-image",
		title: "Rotate Image",
		difficulty: "Medium",
		topics: ["Math & Geometry"],
		companies: ["Uber", "Bloomberg", "Google"],
		order: 252,
	},
	{
		id: "spiral-matrix",
		title: "Spiral Matrix",
		difficulty: "Medium",
		topics: ["Math & Geometry"],
		companies: ["LinkedIn", "Meta"],
		order: 253,
	},
	{
		id: "spiral-matrix-ii",
		title: "Spiral Matrix II",
		difficulty: "Medium",
		topics: ["Math & Geometry"],
		companies: ["Bloomberg", "Uber", "Microsoft"],
		order: 254,
	},
	{
		id: "reshape-the-matrix",
		title: "Reshape the Matrix",
		difficulty: "Easy",
		topics: ["Math & Geometry"],
		companies: ["Yahoo", "Cisco", "LinkedIn", "PayPal"],
		order: 255,
	},
	{
		id: "happy-number",
		title: "Happy Number",
		difficulty: "Easy",
		topics: ["Math & Geometry"],
		companies: ["Bloomberg", "Uber"],
		order: 256,
	},
	{
		id: "pow",
		title: "Pow(x, n)",
		difficulty: "Medium",
		topics: ["Math & Geometry"],
		companies: ["Amazon", "Meta", "ByteDance", "Snap"],
		order: 257,
	},
	{
		id: "multiply-strings",
		title: "Multiply Strings",
		difficulty: "Medium",
		topics: ["Math & Geometry"],
		companies: ["Goldman Sachs", "LinkedIn", "Google"],
		order: 258,
	},
	{
		id: "detect-squares",
		title: "Detect Squares",
		difficulty: "Medium",
		topics: ["Math & Geometry"],
		companies: ["Oracle", "Google", "Visa", "Twitter"],
		order: 259,
	},
	{
		id: "excel-sheet-column-number",
		title: "Excel Sheet Column Number",
		difficulty: "Easy",
		topics: ["Math & Geometry"],
		companies: ["Meta", "Google"],
		order: 260,
	},
	{
		id: "palindrome-number",
		title: "Palindrome Number",
		difficulty: "Easy",
		topics: ["Math & Geometry"],
		companies: ["Amazon", "Pinterest"],
		order: 261,
	},
	{
		id: "number-of-1-bits",
		title: "Number of 1 Bits",
		difficulty: "Easy",
		topics: ["Bit Manipulation"],
		companies: ["Apple", "Microsoft", "Bloomberg", "Visa"],
		order: 262,
	},
	{
		id: "counting-bits",
		title: "Counting Bits",
		difficulty: "Easy",
		topics: ["Bit Manipulation"],
		companies: ["Twitter", "Meta", "Microsoft"],
		order: 263,
	},
	{
		id: "reverse-bits",
		title: "Reverse Bits",
		difficulty: "Easy",
		topics: ["Bit Manipulation"],
		companies: ["Netflix", "Airbnb"],
		order: 264,
	},
	{
		id: "missing-number-ii",
		title: "Missing Number II",
		difficulty: "Easy",
		topics: ["Bit Manipulation"],
		companies: ["Amazon", "Google", "Atlassian"],
		order: 265,
	},
	{
		id: "sum-of-two-integers",
		title: "Sum of Two Integers",
		difficulty: "Medium",
		topics: ["Bit Manipulation"],
		companies: ["Apple", "Walmart Labs", "Snap", "Amazon"],
		order: 266,
	},
	{
		id: "bitwise-and-of-numbers-range",
		title: "Bitwise AND of Numbers Range",
		difficulty: "Medium",
		topics: ["Bit Manipulation"],
		companies: ["Twitter", "Microsoft", "Meta", "Google"],
		order: 267,
	},
	{
		id: "power-of-two",
		title: "Power of Two",
		difficulty: "Easy",
		topics: ["Bit Manipulation"],
		companies: ["Meta", "Adobe", "Goldman Sachs"],
		order: 268,
	},
	{
		id: "power-of-four",
		title: "Power of Four",
		difficulty: "Easy",
		topics: ["Bit Manipulation"],
		companies: ["Spotify", "Amazon"],
		order: 269,
	},
	{
		id: "single-number-iv",
		title: "Single Number IV",
		difficulty: "Easy",
		topics: ["Bit Manipulation"],
		companies: ["LinkedIn", "Spotify", "Airbnb", "Uber"],
		order: 270,
	},
	{
		id: "total-hamming-distance",
		title: "Total Hamming Distance",
		difficulty: "Medium",
		topics: ["Bit Manipulation"],
		companies: ["Atlassian", "Microsoft", "Meta"],
		order: 271,
	},
	{
		id: "design-hashmap",
		title: "Design HashMap",
		difficulty: "Easy",
		topics: ["Design"],
		companies: ["Snap", "Google", "Oracle", "Apple"],
		order: 272,
	},
	{
		id: "design-hashset",
		title: "Design HashSet",
		difficulty: "Easy",
		topics: ["Design"],
		companies: ["Salesforce", "Amazon"],
		order: 273,
	},
	{
		id: "insert-delete-getrandom-o",
		title: "Insert Delete GetRandom O(1)",
		difficulty: "Medium",
		topics: ["Design"],
		companies: ["Apple", "Netflix", "DoorDash", "Oracle"],
		order: 274,
	},
	{
		id: "design-circular-queue",
		title: "Design Circular Queue",
		difficulty: "Medium",
		topics: ["Design"],
		companies: ["Meta", "Adobe"],
		order: 275,
	},
	{
		id: "design-underground-system",
		title: "Design Underground System",
		difficulty: "Medium",
		topics: ["Design"],
		companies: ["Google", "Apple", "LinkedIn"],
		order: 276,
	},
	{
		id: "design-parking-system",
		title: "Design Parking System",
		difficulty: "Easy",
		topics: ["Design"],
		companies: ["Apple", "Meta"],
		order: 277,
	},
	{
		id: "design-a-leaderboard",
		title: "Design a Leaderboard",
		difficulty: "Medium",
		topics: ["Design"],
		companies: ["Uber", "Microsoft"],
		order: 278,
	},
	{
		id: "design-browser-history",
		title: "Design Browser History",
		difficulty: "Medium",
		topics: ["Design"],
		companies: ["PayPal", "Spotify"],
		order: 279,
	},
	{
		id: "design-file-system",
		title: "Design File System",
		difficulty: "Medium",
		topics: ["Design"],
		companies: ["Bloomberg", "Snap", "Apple", "Uber"],
		order: 280,
	},
	{
		id: "design-snake-game",
		title: "Design Snake Game",
		difficulty: "Medium",
		topics: ["Design"],
		companies: ["ByteDance", "Salesforce", "Spotify", "Microsoft"],
		order: 281,
	},
	{
		id: "search-a-2d-matrix-ii",
		title: "Search a 2D Matrix II",
		difficulty: "Medium",
		topics: ["Matrix"],
		companies: ["Google", "Bloomberg", "Apple", "Airbnb"],
		order: 282,
	},
	{
		id: "number-of-distinct-islands",
		title: "Number of Distinct Islands",
		difficulty: "Medium",
		topics: ["Matrix"],
		companies: ["Apple", "Snap"],
		order: 283,
	},
	{
		id: "toeplitz-matrix",
		title: "Toeplitz Matrix",
		difficulty: "Easy",
		topics: ["Matrix"],
		companies: ["Bloomberg", "Pinterest", "Uber"],
		order: 284,
	},
	{
		id: "game-of-life",
		title: "Game of Life",
		difficulty: "Medium",
		topics: ["Matrix"],
		companies: ["LinkedIn", "Apple", "ByteDance"],
		order: 285,
	},
	{
		id: "diagonal-traverse",
		title: "Diagonal Traverse",
		difficulty: "Medium",
		topics: ["Matrix"],
		companies: ["Meta", "Microsoft"],
		order: 286,
	},
	{
		id: "kth-smallest-element-in-a-sorted-matrix",
		title: "Kth Smallest Element in a Sorted Matrix",
		difficulty: "Medium",
		topics: ["Matrix"],
		companies: ["DoorDash", "Google", "Twitter"],
		order: 287,
	},
	{
		id: "max-increase-to-keep-city-skyline",
		title: "Max Increase to Keep City Skyline",
		difficulty: "Medium",
		topics: ["Matrix"],
		companies: ["Goldman Sachs", "LinkedIn", "Adobe"],
		order: 288,
	},
	{
		id: "cherry-pickup",
		title: "Cherry Pickup",
		difficulty: "Hard",
		topics: ["Matrix"],
		companies: ["Netflix", "Walmart Labs", "Atlassian", "Uber"],
		order: 289,
	},
	{
		id: "shortest-path-in-binary-matrix",
		title: "Shortest Path in Binary Matrix",
		difficulty: "Medium",
		topics: ["Matrix"],
		companies: ["Uber", "Adobe", "Snap", "Microsoft"],
		order: 290,
	},
	{
		id: "longest-common-prefix",
		title: "Longest Common Prefix",
		difficulty: "Easy",
		topics: ["Strings"],
		companies: ["Salesforce", "LinkedIn", "Microsoft"],
		order: 291,
	},
	{
		id: "group-shifted-strings",
		title: "Group Shifted Strings",
		difficulty: "Medium",
		topics: ["Strings"],
		companies: ["Two Sigma", "Microsoft"],
		order: 292,
	},
	{
		id: "string-to-integer",
		title: "String to Integer (atoi)",
		difficulty: "Medium",
		topics: ["Strings"],
		companies: ["Apple", "Bloomberg", "Meta"],
		order: 293,
	},
	{
		id: "zigzag-conversion",
		title: "Zigzag Conversion",
		difficulty: "Medium",
		topics: ["Strings"],
		companies: ["Google", "Snap", "Apple"],
		order: 294,
	},
	{
		id: "compare-version-numbers",
		title: "Compare Version Numbers",
		difficulty: "Medium",
		topics: ["Strings"],
		companies: ["Cisco", "Bloomberg", "Oracle"],
		order: 295,
	},
	{
		id: "ransom-note",
		title: "Ransom Note",
		difficulty: "Easy",
		topics: ["Strings"],
		companies: ["DoorDash", "Pinterest"],
		order: 296,
	},
	{
		id: "isomorphic-strings",
		title: "Isomorphic Strings",
		difficulty: "Easy",
		topics: ["Strings"],
		companies: ["Goldman Sachs", "Oracle", "Amazon"],
		order: 297,
	},
	{
		id: "word-pattern",
		title: "Word Pattern",
		difficulty: "Easy",
		topics: ["Strings"],
		companies: ["Microsoft", "Pinterest", "LinkedIn"],
		order: 298,
	},
	{
		id: "one-edit-distance",
		title: "One Edit Distance",
		difficulty: "Medium",
		topics: ["Strings"],
		companies: ["Uber", "Airbnb"],
		order: 299,
	},
	{
		id: "roman-to-integer",
		title: "Roman to Integer",
		difficulty: "Easy",
		topics: ["Strings"],
		companies: ["Google", "Visa", "LinkedIn"],
		order: 300,
	},
	{
		id: "integer-to-roman",
		title: "Integer to Roman",
		difficulty: "Medium",
		topics: ["Strings"],
		companies: ["LinkedIn", "Yahoo"],
		order: 301,
	},
	{
		id: "length-of-last-word",
		title: "Length of Last Word",
		difficulty: "Easy",
		topics: ["Strings"],
		companies: ["Amazon", "Atlassian", "Google", "Microsoft"],
		order: 302,
	},
	{
		id: "text-justification",
		title: "Text Justification",
		difficulty: "Hard",
		topics: ["Strings"],
		companies: ["Goldman Sachs", "Yahoo", "Apple", "Uber"],
		order: 303,
	},
	{
		id: "repeated-substring-pattern",
		title: "Repeated Substring Pattern",
		difficulty: "Easy",
		topics: ["Strings"],
		companies: ["ByteDance", "Bloomberg"],
		order: 304,
	},
	{
		id: "count-and-say",
		title: "Count and Say",
		difficulty: "Medium",
		topics: ["Strings"],
		companies: ["Meta", "Visa"],
		order: 305,
	},
];
