import assert from "assert";
import { Problem } from "../types/problem";

function referenceCountAndSay(n: number): string {
	let result = "1";
	for (let i = 1; i < n; i++) {
		let next = "";
		let count = 1;
		for (let j = 1; j <= result.length; j++) {
			if (result[j] === result[j - 1]) {
				count++;
			} else {
				next += count + result[j - 1];
				count = 1;
			}
		}
		result = next;
	}
	return result;
}

export const countAndSayHandler = (fn: any) => {
	try {
		const tests: number[] = [1, 2, 3, 4, 5, 6];
		for (const n of tests) {
			const expected = referenceCountAndSay(n);
			const result = fn(n);
			assert.strictEqual(result, expected);
		}
		return true;
	} catch (error: any) {
		console.log("Error from countAndSayHandler: ", error);
		throw new Error(error);
	}
};

const starterCodeCountAndSayJS = `function countAndSay(n) {
  // Write your code here
};`;

export const countAndSay: Problem = {
	id: "count-and-say",
	title: "305. Count and Say",
	problemStatement: `<p class='mt-3'>
    The count-and-say sequence starts with <code>"1"</code>. Each following term is generated by
    reading off the previous term: for each run of the same digit, write the number of times it
    repeats, then the digit itself.
  </p>
  <p class='mt-3'>
    For example, <code>"1"</code> is read as "one 1" &rarr; <code>"11"</code>, which is read as
    "two 1s" &rarr; <code>"21"</code>, which is read as "one 2, one 1" &rarr; <code>"1211"</code>.
  </p>
  <p class='mt-3'>Given a positive integer <code>n</code>, return the <code>n</code>th term of this sequence as a string.</p>
  `,
	examples: [
		{
			id: 0,
			inputText: `n = 1`,
			outputText: `"1"`,
		},
		{
			id: 1,
			inputText: `n = 4`,
			outputText: `"1211"`,
			explanation: "1 -> 11 -> 21 -> 1211.",
		},
		{
			id: 2,
			inputText: `n = 5`,
			outputText: `"111221"`,
			explanation: "1211 is read as \"one 1, one 2, two 1s\" -> 111221.",
		},
	],
	constraints: `<li class='mt-2'><code>1 &lt;= n &lt;= 30</code></li>`,
	starterCode: starterCodeCountAndSayJS,
	handlerFunction: countAndSayHandler,
	starterFunctionName: "function countAndSay(",
	order: 305,
};
