// Reference Big-O complexity for each problem's *optimal* known solution.
// Shown as informational context in the problem description -- not derived
// from the user's own submitted code (accurately inferring asymptotic
// complexity from arbitrary code isn't reliably computable).

export type ComplexityInfo = {
	time: string;
	space: string;
};

export const PROBLEM_COMPLEXITY: Record<string, ComplexityInfo> = {
	"two-sum": { time: "O(n)", space: "O(n)" },
	"contains-duplicate": { time: "O(n)", space: "O(n)" },
	"valid-anagram": { time: "O(n)", space: "O(1)" },
	"group-anagrams": { time: "O(n · k)", space: "O(n · k)" },
	"top-k-frequent-elements": { time: "O(n)", space: "O(n)" },
	"product-of-array-except-self": { time: "O(n)", space: "O(1)" },
	"longest-consecutive-sequence": { time: "O(n)", space: "O(n)" },
	"encode-and-decode-strings": { time: "O(n)", space: "O(n)" },
	"valid-sudoku": { time: "O(1)", space: "O(1)" },
	"majority-element": { time: "O(n)", space: "O(1)" },
	"missing-number": { time: "O(n)", space: "O(1)" },
	"find-all-numbers-disappeared-in-an-array": { time: "O(n)", space: "O(1)" },
	"single-number": { time: "O(n)", space: "O(1)" },
	"single-number-ii": { time: "O(n)", space: "O(1)" },
	"single-number-iii": { time: "O(n)", space: "O(1)" },
	"intersection-of-two-arrays": { time: "O(m + n)", space: "O(m + n)" },
	"intersection-of-two-arrays-ii": { time: "O(m + n)", space: "O(min(m, n))" },
	"sort-colors": { time: "O(n)", space: "O(1)" },
	"move-zeroes": { time: "O(n)", space: "O(1)" },
	"rotate-array": { time: "O(n)", space: "O(1)" },
	"best-time-to-buy-and-sell-stock": { time: "O(n)", space: "O(1)" },
	"best-time-to-buy-and-sell-stock-ii": { time: "O(n)", space: "O(1)" },
	"subarray-sum-equals-k": { time: "O(n)", space: "O(n)" },
	"continuous-subarray-sum": { time: "O(n)", space: "O(min(n, k))" },
	"merge-sorted-array": { time: "O(m + n)", space: "O(1)" },
	"remove-duplicates-from-sorted-array": { time: "O(n)", space: "O(1)" },
	"remove-element": { time: "O(n)", space: "O(1)" },
	"plus-one": { time: "O(n)", space: "O(1)" },
	"pascal-s-triangle": { time: "O(n²)", space: "O(n²)" },
	"first-missing-positive": { time: "O(n)", space: "O(1)" },
	"set-matrix-zeroes": { time: "O(m · n)", space: "O(1)" },
	"valid-palindrome": { time: "O(n)", space: "O(1)" },
	"3sum": { time: "O(n²)", space: "O(1)" },
	"3sum-closest": { time: "O(n²)", space: "O(1)" },
	"4sum": { time: "O(n³)", space: "O(1)" },
	"container-with-most-water": { time: "O(n)", space: "O(1)" },
	"trapping-rain-water": { time: "O(n)", space: "O(1)" },
	"sort-array-by-parity": { time: "O(n)", space: "O(1)" },
	"remove-duplicates-from-sorted-array-ii": { time: "O(n)", space: "O(1)" },
	"backspace-string-compare": { time: "O(n + m)", space: "O(1)" },
	"squares-of-a-sorted-array": { time: "O(n)", space: "O(n)" },
	"reverse-string": { time: "O(n)", space: "O(1)" },
	"boats-to-save-people": { time: "O(n log n)", space: "O(1)" },
	"two-sum-ii-input-array-is-sorted": { time: "O(n)", space: "O(1)" },
	"is-subsequence": { time: "O(n)", space: "O(1)" },
	"reverse-vowels-of-a-string": { time: "O(n)", space: "O(n)" },
	"longest-substring-without-repeating-characters": { time: "O(n)", space: "O(min(n, Σ))" },
	"longest-repeating-character-replacement": { time: "O(n)", space: "O(1)" },
	"permutation-in-string": { time: "O(n)", space: "O(1)" },
	"minimum-window-substring": { time: "O(n + m)", space: "O(Σ)" },
	"sliding-window-maximum": { time: "O(n)", space: "O(k)" },
	"minimum-size-subarray-sum": { time: "O(n)", space: "O(1)" },
	"fruit-into-baskets": { time: "O(n)", space: "O(1)" },
	"max-consecutive-ones-iii": { time: "O(n)", space: "O(1)" },
	"find-all-anagrams-in-a-string": { time: "O(n)", space: "O(1)" },
	"longest-substring-with-at-most-two-distinct-characters": { time: "O(n)", space: "O(1)" },
	"longest-substring-with-at-most-k-distinct-characters": { time: "O(n)", space: "O(k)" },
	"maximum-average-subarray-i": { time: "O(n)", space: "O(1)" },
	"subarrays-with-k-different-integers": { time: "O(n)", space: "O(n)" },
	"grumpy-bookstore-owner": { time: "O(n)", space: "O(1)" },
	"frequency-of-the-most-frequent-element": { time: "O(n log n)", space: "O(1)" },
	"valid-parentheses": { time: "O(n)", space: "O(n)" },
	"min-stack": { time: "O(1) per op", space: "O(n)" },
	"evaluate-reverse-polish-notation": { time: "O(n)", space: "O(n)" },
	"generate-parentheses": { time: "O(4ⁿ / √n)", space: "O(4ⁿ / √n)" },
	"daily-temperatures": { time: "O(n)", space: "O(n)" },
	"car-fleet": { time: "O(n log n)", space: "O(n)" },
	"largest-rectangle-in-histogram": { time: "O(n)", space: "O(n)" },
	"next-greater-element-i": { time: "O(n + m)", space: "O(n)" },
	"next-greater-element-ii": { time: "O(n)", space: "O(n)" },
	"asteroid-collision": { time: "O(n)", space: "O(n)" },
	"decode-string": { time: "O(n)", space: "O(n)" },
	"remove-all-adjacent-duplicates-in-string": { time: "O(n)", space: "O(n)" },
	"simplify-path": { time: "O(n)", space: "O(n)" },
	"basic-calculator": { time: "O(n)", space: "O(n)" },
	"online-stock-span": { time: "O(n) amortized", space: "O(n)" },
	"search-a-2d-matrix": { time: "O(log(m · n))", space: "O(1)" },
	"binary-search": { time: "O(log n)", space: "O(1)" },
	"search-in-rotated-sorted-array": { time: "O(log n)", space: "O(1)" },
	"search-in-rotated-sorted-array-ii": { time: "O(log n) avg", space: "O(1)" },
	"find-minimum-in-rotated-sorted-array": { time: "O(log n)", space: "O(1)" },
	"find-minimum-in-rotated-sorted-array-ii": { time: "O(log n) avg", space: "O(1)" },
	"time-based-key-value-store": { time: "O(log n)", space: "O(n)" },
	"median-of-two-sorted-arrays": { time: "O(log(min(m, n)))", space: "O(1)" },
	"koko-eating-bananas": { time: "O(n log m)", space: "O(1)" },
	"capacity-to-ship-packages-within-d-days": { time: "O(n log(sum − max))", space: "O(1)" },
	"split-array-largest-sum": { time: "O(n log(sum))", space: "O(1)" },
	"find-peak-element": { time: "O(log n)", space: "O(1)" },
	"search-insert-position": { time: "O(log n)", space: "O(1)" },
	"first-bad-version": { time: "O(log n)", space: "O(1)" },
	"find-first-and-last-position-of-element-in-sorted-array": { time: "O(log n)", space: "O(1)" },
	"reverse-linked-list": { time: "O(n)", space: "O(1)" },
	"merge-two-sorted-lists": { time: "O(n + m)", space: "O(1)" },
	"linked-list-cycle": { time: "O(n)", space: "O(1)" },
	"linked-list-cycle-ii": { time: "O(n)", space: "O(1)" },
	"reorder-list": { time: "O(n)", space: "O(1)" },
	"remove-nth-node-from-end-of-list": { time: "O(n)", space: "O(1)" },
	"copy-list-with-random-pointer": { time: "O(n)", space: "O(1)" },
	"add-two-numbers": { time: "O(max(n, m))", space: "O(max(n, m))" },
	"merge-k-sorted-lists": { time: "O(n log k)", space: "O(k)" },
	"lru-cache": { time: "O(1) per op", space: "O(capacity)" },
	"lfu-cache": { time: "O(1) per op", space: "O(capacity)" },
	"palindrome-linked-list": { time: "O(n)", space: "O(1)" },
	"odd-even-linked-list": { time: "O(n)", space: "O(1)" },
	"swap-nodes-in-pairs": { time: "O(n)", space: "O(1)" },
	"rotate-list": { time: "O(n)", space: "O(1)" },
	"maximum-depth-of-binary-tree": { time: "O(n)", space: "O(h)" },
	"same-tree": { time: "O(n)", space: "O(h)" },
	"invert-binary-tree": { time: "O(n)", space: "O(h)" },
	"subtree-of-another-tree": { time: "O(m · n)", space: "O(h)" },
	"binary-tree-level-order-traversal": { time: "O(n)", space: "O(n)" },
	"binary-tree-zigzag-level-order-traversal": { time: "O(n)", space: "O(n)" },
	"binary-tree-right-side-view": { time: "O(n)", space: "O(n)" },
	"count-good-nodes-in-binary-tree": { time: "O(n)", space: "O(h)" },
	"validate-binary-search-tree": { time: "O(n)", space: "O(h)" },
	"kth-smallest-element-in-a-bst": { time: "O(h + k)", space: "O(h)" },
	"construct-binary-tree-from-preorder-and-inorder-traversal": { time: "O(n)", space: "O(n)" },
	"binary-tree-maximum-path-sum": { time: "O(n)", space: "O(h)" },
	"serialize-and-deserialize-binary-tree": { time: "O(n)", space: "O(n)" },
	"lowest-common-ancestor-of-a-binary-search-tree": { time: "O(h)", space: "O(1)" },
	"lowest-common-ancestor-of-a-binary-tree": { time: "O(n)", space: "O(h)" },
	"balanced-binary-tree": { time: "O(n)", space: "O(h)" },
	"diameter-of-binary-tree": { time: "O(n)", space: "O(h)" },
	"symmetric-tree": { time: "O(n)", space: "O(h)" },
	"path-sum": { time: "O(n)", space: "O(h)" },
	"path-sum-ii": { time: "O(n²) worst", space: "O(n)" },
	"flatten-binary-tree-to-linked-list": { time: "O(n)", space: "O(h)" },
	"binary-tree-inorder-traversal": { time: "O(n)", space: "O(h)" },
	"binary-tree-preorder-traversal": { time: "O(n)", space: "O(h)" },
	"binary-tree-postorder-traversal": { time: "O(n)", space: "O(h)" },
	"convert-sorted-array-to-binary-search-tree": { time: "O(n)", space: "O(log n)" },
	"implement-trie": { time: "O(k) per op", space: "O(n · k)" },
	"design-add-and-search-words-data-structure": { time: "O(k) add, O(26^k) search", space: "O(n · k)" },
	"word-search-ii": { time: "O(m · n · 4^L)", space: "O(Σ word lengths)" },
	"replace-words": { time: "O(n)", space: "O(n)" },
	"longest-word-in-dictionary": { time: "O(n · k)", space: "O(n · k)" },
	"kth-largest-element-in-an-array": { time: "O(n log k)", space: "O(k)" },
	"kth-largest-element-in-a-stream": { time: "O(log k) per op", space: "O(k)" },
	"last-stone-weight": { time: "O(n log n)", space: "O(n)" },
	"k-closest-points-to-origin": { time: "O(n log k)", space: "O(k)" },
	"task-scheduler": { time: "O(n)", space: "O(1)" },
	"design-twitter": { time: "O(log n) per op", space: "O(n)" },
	"find-median-from-data-stream": { time: "O(log n) add, O(1) find", space: "O(n)" },
	"top-k-frequent-words": { time: "O(n log k)", space: "O(n)" },
	"reorganize-string": { time: "O(n log k)", space: "O(n)" },
	"ugly-number-ii": { time: "O(n)", space: "O(n)" },
	"subsets": { time: "O(n · 2ⁿ)", space: "O(n · 2ⁿ)" },
	"subsets-ii": { time: "O(n · 2ⁿ)", space: "O(n · 2ⁿ)" },
	"combination-sum": { time: "O(2ⁿ)", space: "O(target)" },
	"combination-sum-ii": { time: "O(2ⁿ)", space: "O(n)" },
	"permutations": { time: "O(n · n!)", space: "O(n · n!)" },
	"permutations-ii": { time: "O(n · n!)", space: "O(n · n!)" },
	"word-search": { time: "O(m · n · 4^L)", space: "O(L)" },
	"palindrome-partitioning": { time: "O(n · 2ⁿ)", space: "O(n)" },
	"letter-combinations-of-a-phone-number": { time: "O(4ⁿ · n)", space: "O(n)" },
	"n-queens": { time: "O(n!)", space: "O(n²)" },
	"n-queens-ii": { time: "O(n!)", space: "O(n)" },
	"sudoku-solver": { time: "O(9^m) (m empty cells)", space: "O(1)" },
	"combinations": { time: "O(C(n, k) · k)", space: "O(k)" },
	"restore-ip-addresses": { time: "O(1) (bounded)", space: "O(1)" },
	"unique-paths-iii": { time: "O(4^(m · n))", space: "O(m · n)" },
	"number-of-islands": { time: "O(m · n)", space: "O(m · n)" },
	"max-area-of-island": { time: "O(m · n)", space: "O(m · n)" },
	"clone-graph": { time: "O(n + e)", space: "O(n)" },
	"walls-and-gates": { time: "O(m · n)", space: "O(m · n)" },
	"rotting-oranges": { time: "O(m · n)", space: "O(m · n)" },
	"pacific-atlantic-water-flow": { time: "O(m · n)", space: "O(m · n)" },
	"surrounded-regions": { time: "O(m · n)", space: "O(m · n)" },
	"course-schedule": { time: "O(V + E)", space: "O(V + E)" },
	"course-schedule-ii": { time: "O(V + E)", space: "O(V + E)" },
	"graph-valid-tree": { time: "O(V + E)", space: "O(V + E)" },
	"number-of-connected-components-in-an-undirected-graph": { time: "O(V + E)", space: "O(V)" },
	"redundant-connection": { time: "O(V + E)", space: "O(V)" },
	"word-ladder": { time: "O(n² · k)", space: "O(n · k)" },
	"word-ladder-ii": { time: "O(n² · k)", space: "O(n · k)" },
	"reconstruct-itinerary": { time: "O(E log E)", space: "O(E)" },
	"evaluate-division": { time: "O(q · (V + E))", space: "O(V + E)" },
	"is-graph-bipartite": { time: "O(V + E)", space: "O(V)" },
	"minimum-height-trees": { time: "O(V)", space: "O(V)" },
	"all-paths-from-source-to-target": { time: "O(2^V · V)", space: "O(V)" },
	"flood-fill": { time: "O(m · n)", space: "O(m · n)" },
	"network-delay-time": { time: "O(E log V)", space: "O(V + E)" },
	"cheapest-flights-within-k-stops": { time: "O(E · k)", space: "O(V)" },
	"swim-in-rising-water": { time: "O(n² log n)", space: "O(n²)" },
	"alien-dictionary": { time: "O(C)", space: "O(1)" },
	"min-cost-to-connect-all-points": { time: "O(n² log n)", space: "O(n²)" },
	"path-with-maximum-probability": { time: "O(E log V)", space: "O(V + E)" },
	"critical-connections-in-a-network": { time: "O(V + E)", space: "O(V + E)" },
	"number-of-provinces": { time: "O(n²)", space: "O(n)" },
	"accounts-merge": { time: "O(n log n)", space: "O(n)" },
	"find-the-city-with-the-smallest-number-of-neighbors-at-a-threshold-distance": { time: "O(V³)", space: "O(V²)" },
	"climbing-stairs": { time: "O(n)", space: "O(1)" },
	"house-robber": { time: "O(n)", space: "O(1)" },
	"house-robber-ii": { time: "O(n)", space: "O(1)" },
	"longest-palindromic-substring": { time: "O(n²)", space: "O(1)" },
	"palindromic-substrings": { time: "O(n²)", space: "O(1)" },
	"decode-ways": { time: "O(n)", space: "O(1)" },
	"coin-change": { time: "O(n · amount)", space: "O(amount)" },
	"coin-change-ii": { time: "O(n · amount)", space: "O(amount)" },
	"maximum-product-subarray": { time: "O(n)", space: "O(1)" },
	"word-break": { time: "O(n²)", space: "O(n)" },
	"longest-increasing-subsequence": { time: "O(n log n)", space: "O(n)" },
	"partition-equal-subset-sum": { time: "O(n · sum)", space: "O(sum)" },
	"combination-sum-iv": { time: "O(target · n)", space: "O(target)" },
	"perfect-squares": { time: "O(n · √n)", space: "O(n)" },
	"integer-break": { time: "O(n)", space: "O(1)" },
	"delete-and-earn": { time: "O(n + max)", space: "O(max)" },
	"domino-and-tromino-tiling": { time: "O(n)", space: "O(1)" },
	"min-cost-climbing-stairs": { time: "O(n)", space: "O(1)" },
	"fibonacci-number": { time: "O(n)", space: "O(1)" },
	"jump-game-ii": { time: "O(n)", space: "O(1)" },
	"unique-paths": { time: "O(m · n)", space: "O(n)" },
	"unique-paths-ii": { time: "O(m · n)", space: "O(n)" },
	"minimum-path-sum": { time: "O(m · n)", space: "O(n)" },
	"longest-common-subsequence": { time: "O(m · n)", space: "O(min(m, n))" },
	"best-time-to-buy-and-sell-stock-with-cooldown": { time: "O(n)", space: "O(1)" },
	"best-time-to-buy-and-sell-stock-iii": { time: "O(n)", space: "O(1)" },
	"best-time-to-buy-and-sell-stock-iv": { time: "O(n · k)", space: "O(k)" },
	"edit-distance": { time: "O(m · n)", space: "O(min(m, n))" },
	"interleaving-string": { time: "O(m · n)", space: "O(n)" },
	"distinct-subsequences": { time: "O(m · n)", space: "O(n)" },
	"longest-increasing-path-in-a-matrix": { time: "O(m · n)", space: "O(m · n)" },
	"maximal-square": { time: "O(m · n)", space: "O(n)" },
	"regular-expression-matching": { time: "O(m · n)", space: "O(m · n)" },
	"wildcard-matching": { time: "O(m · n)", space: "O(m · n)" },
	"target-sum": { time: "O(n · sum)", space: "O(sum)" },
	"maximum-subarray": { time: "O(n)", space: "O(1)" },
	"jump-game": { time: "O(n)", space: "O(1)" },
	"gas-station": { time: "O(n)", space: "O(1)" },
	"hand-of-straights": { time: "O(n log n)", space: "O(n)" },
	"merge-triplets-to-form-target-triplet": { time: "O(n)", space: "O(1)" },
	"valid-parenthesis-string": { time: "O(n)", space: "O(1)" },
	"candy": { time: "O(n)", space: "O(n)" },
	"lemonade-change": { time: "O(n)", space: "O(1)" },
	"assign-cookies": { time: "O(n log n)", space: "O(1)" },
	"queue-reconstruction-by-height": { time: "O(n²)", space: "O(n)" },
	"jump-game-iii": { time: "O(n)", space: "O(n)" },
	"non-overlapping-intervals": { time: "O(n log n)", space: "O(1)" },
	"partition-labels": { time: "O(n)", space: "O(1)" },
	"minimum-number-of-arrows-to-burst-balloons": { time: "O(n log n)", space: "O(1)" },
	"two-city-scheduling": { time: "O(n log n)", space: "O(1)" },
	"merge-intervals": { time: "O(n log n)", space: "O(n)" },
	"insert-interval": { time: "O(n)", space: "O(n)" },
	"meeting-rooms": { time: "O(n log n)", space: "O(1)" },
	"meeting-rooms-ii": { time: "O(n log n)", space: "O(n)" },
	"interval-list-intersections": { time: "O(m + n)", space: "O(m + n)" },
	"my-calendar-i": { time: "O(n) per op", space: "O(n)" },
	"employee-free-time": { time: "O(n log n)", space: "O(n)" },
	"car-pooling": { time: "O(n log n)", space: "O(n)" },
	"minimum-interval-to-include-each-query": { time: "O((n + q) log n)", space: "O(n + q)" },
	"remove-covered-intervals": { time: "O(n log n)", space: "O(1)" },
	"rotate-image": { time: "O(n²)", space: "O(1)" },
	"spiral-matrix": { time: "O(m · n)", space: "O(1)" },
	"spiral-matrix-ii": { time: "O(n²)", space: "O(1)" },
	"reshape-the-matrix": { time: "O(m · n)", space: "O(m · n)" },
	"happy-number": { time: "O(log n)", space: "O(log n)" },
	"pow": { time: "O(log n)", space: "O(1)" },
	"multiply-strings": { time: "O(m · n)", space: "O(m + n)" },
	"detect-squares": { time: "O(1) add, O(√n) query", space: "O(n)" },
	"excel-sheet-column-number": { time: "O(n)", space: "O(1)" },
	"palindrome-number": { time: "O(log n)", space: "O(1)" },
	"number-of-1-bits": { time: "O(1)", space: "O(1)" },
	"counting-bits": { time: "O(n)", space: "O(n)" },
	"reverse-bits": { time: "O(1)", space: "O(1)" },
	"missing-number-ii": { time: "O(n)", space: "O(1)" },
	"sum-of-two-integers": { time: "O(1)", space: "O(1)" },
	"bitwise-and-of-numbers-range": { time: "O(1)", space: "O(1)" },
	"power-of-two": { time: "O(1)", space: "O(1)" },
	"power-of-four": { time: "O(1)", space: "O(1)" },
	"single-number-iv": { time: "O(n)", space: "O(1)" },
	"total-hamming-distance": { time: "O(n)", space: "O(1)" },
	"design-hashmap": { time: "O(1) avg per op", space: "O(n)" },
	"design-hashset": { time: "O(1) avg per op", space: "O(n)" },
	"insert-delete-getrandom-o": { time: "O(1) per op", space: "O(n)" },
	"design-circular-queue": { time: "O(1) per op", space: "O(k)" },
	"design-underground-system": { time: "O(1) per op", space: "O(n)" },
	"design-parking-system": { time: "O(1) per op", space: "O(1)" },
	"design-a-leaderboard": { time: "O(log n) per op", space: "O(n)" },
	"design-browser-history": { time: "O(1) amortized", space: "O(n)" },
	"design-file-system": { time: "O(k) per op", space: "O(n)" },
	"design-snake-game": { time: "O(1) per move", space: "O(n)" },
	"search-a-2d-matrix-ii": { time: "O(m + n)", space: "O(1)" },
	"number-of-distinct-islands": { time: "O(m · n)", space: "O(m · n)" },
	"toeplitz-matrix": { time: "O(m · n)", space: "O(1)" },
	"game-of-life": { time: "O(m · n)", space: "O(1)" },
	"diagonal-traverse": { time: "O(m · n)", space: "O(1)" },
	"kth-smallest-element-in-a-sorted-matrix": { time: "O(n log(max − min))", space: "O(1)" },
	"max-increase-to-keep-city-skyline": { time: "O(n²)", space: "O(n)" },
	"cherry-pickup": { time: "O(n³)", space: "O(n²)" },
	"shortest-path-in-binary-matrix": { time: "O(n²)", space: "O(n²)" },
	"longest-common-prefix": { time: "O(Σ lengths)", space: "O(1)" },
	"group-shifted-strings": { time: "O(n · k)", space: "O(n · k)" },
	"string-to-integer": { time: "O(n)", space: "O(1)" },
	"zigzag-conversion": { time: "O(n)", space: "O(1)" },
	"compare-version-numbers": { time: "O(n + m)", space: "O(n + m)" },
	"ransom-note": { time: "O(n + m)", space: "O(1)" },
	"isomorphic-strings": { time: "O(n)", space: "O(1)" },
	"word-pattern": { time: "O(n)", space: "O(n)" },
	"one-edit-distance": { time: "O(n)", space: "O(1)" },
	"roman-to-integer": { time: "O(n)", space: "O(1)" },
	"integer-to-roman": { time: "O(1)", space: "O(1)" },
	"length-of-last-word": { time: "O(n)", space: "O(1)" },
	"text-justification": { time: "O(n)", space: "O(n)" },
	"repeated-substring-pattern": { time: "O(n)", space: "O(n)" },
	"count-and-say": { time: "O(2ⁿ)", space: "O(2ⁿ)" },
};
